import pizzaImg from './images/Pizza-thick.png';


export const arrayForList = [
    {   name: "Pizza",
        src: pizzaImg,
        id: 1,
        price: 5,
     },
     {  name: "Burger",
        src: '/images/Burger.jpg', 
        id: 2,
        price: 5,
     },
     {  name: "Momo",
        src: '/images/Momo-food.png',
        id: 3,
        price: 5,
     },
     {  name: "Hotdog",
        src: '/images/Hotdog.png',
        id: 4,
        price: 5,
     },
     {  name: "Chicken-Burger",
        src: '/images/Chicken-Burger.png',
        id: 5,
        price: 5,
     },
     {  name: "Chicken-Pizza",
        src: '/images/Pizza-thick.png',
        id: 6,
        price: 5,
     },
     {  name: "Dominos",
        src: '/images/Pizza-thick.png',
        id: 7,
        price: 5,
     },
     {  name: "McDonald Special", 
        src: '/images/Set-of-food.jpeg',
        id: 8,
        price: 5,
     }
]
